# This file contains values from Cookiecutter

default_context:
  project_name: "polyharmonics"
  project_description: "Ortogonal Polynomials in the unit sphere."
  organization: "UGR"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.8
  github_name: "ComicIvans"
  email: "isalidocobo@gmail.com"
  version: "0.0.1"
  line_length: "88"
  create_example_template: "cli"
